### ISSUE TITLE
Error while dynamically changing settings in sbt shell 

### ISSUE THREAD

**Issue by olafurpg** [scalameta/semanticdb-sbt#15]
```
> scalding: set scalacOptions in ThisBuild += "-Ywarn-unused-import"
java.lang.IllegalArgumentException: 'other' is different type of Path
	at sun.nio.fs.UnixPath.relativize(UnixPath.java:416)
	at sun.nio.fs.UnixPath.relativize(UnixPath.java:43)
	at scala.meta.internal.sbthost.SbthostConfig.relativePath(ConfigOps.scala:9)
```

**Comment by dwijnand** [comment]
IntelliJ's import (I think only in the context of using the new "Use sbt shell for build and import" option) uses `set`, and therefore also triggers this.

Temporarily commenting out adding the `semanticdb-sbt` compiler plugin in `plugins.sbt` worked around the issue.

**Comment by toebbel** [comment]
I have the same issue and have to use the work-around as mentioned above.

**Comment by olafurpg** [comment]
Please note that semanticdb-sbt was an experimental feature that is no longer under active development. @toebbel
